#
# ~/.zshenv
#

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"
export ZSHRCD="${ZDOTDIR}/rc.d"
export ZSHFND="${ZDOTDIR}/fn.d"
export ZPLUGINDIR="${XDG_DATA_HOME}/zsh/plugins"
export ZSH_CACHE_DIR="${XDG_CACHE_HOME}/zsh"
export {TMPDIR,TMP,TEMP}=$HOME/tmp

